# Generated by Django 4.2 on 2026-01-29 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('CALL_CENTER', 'Call Center'), ('CAMPO', 'Campo')], max_length=20)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10)),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('cliente_dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('cliente_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('cliente_direccion', models.TextField(verbose_name='Dirección')),
                ('cliente_correo', models.TextField(verbose_name='Correo')),
                ('cliente_genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('producto_servicio', models.CharField(max_length=200, verbose_name='Producto/Servicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('sec', models.CharField(blank=True, max_length=50, verbose_name='SEC')),
                ('sot', models.CharField(blank=True, max_length=50, verbose_name='SOT')),
                ('fecha_instalacion_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Instalación Programada')),
                ('fecha_instalacion_real', models.DateField(blank=True, null=True, verbose_name='Fecha Instalación Real')),
                ('estado', models.CharField(choices=[('PENDIENTE_BO', 'Pendiente Back Office'), ('PENDIENTE_AUDIO', 'Pendiente Audio'), ('AUDIO_REVISION', 'Audio en Revisión'), ('AUDIO_NO_CONFORME', 'Audio No Conforme'), ('PENDIENTE_INSTALACION', 'Pendiente Instalación'), ('EN_EJECUCION', 'En Ejecución'), ('INSTALADA', 'Instalada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE_BO', max_length=30)),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(limit_choices_to={'rol': 'ASESOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
